---
# tasks file for demo2
- name: implement file tasks and handlers
  yum: 
   name: httpd
   state: present
- name: create a webpage
  copy:
   src: def.html
   dest: /var/www/html/index.html
  notify: role_demo2 
