---
- name: collection manage hosts information
  hosts: all
  tasks:
  - name: send jinja info to managed hosts
    template:
     src: /home/newuser/demonstration/jinja.j2
     dest: /tmp/training
     mode: 0644

